Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', include('app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blog/app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path(r'', views.ArticleListView.as_view(), name='main'),
	path('<slug:slug>/', views.ArticleDetailView.as_view()),
    path('category/<slug:slug>', views.ArticleListCategoryView.as_view()),
]

Blog/app/models.py
from datetime import datetime
from django.db import models
from django.urls import reverse
from tinymce import models as tm

# Create your models here.


class Category(models.Model):
	category_name = models.CharField(max_length=255, unique=True)
	category_slug = models.SlugField(max_length=255)

	def __str__(self):
		return self.category_slug


class Article(models.Model):
	meta_title = models.CharField(max_length=255)
	article_header_image_url = models.CharField(max_length=255)
	article_description = models.TextField()
	article_title = models.CharField(max_length=255)
	article_content = tm.HTMLField()
	article_published = models.DateTimeField("date publiched", default=datetime.now())
	article_slug = models.SlugField(max_length=255, unique=True)
	article_category = models.ManyToManyField(Category)
	is_public = models.BooleanField(default=False)

	def __str__(self):
		return self.article_title

	def get_absolute_url(self):
		return reverse('article', args=[str(self.article_slug)])


class Image(models.Model):
    name = models.CharField(max_length=255, default='image')
    image = models.ImageField(upload_to='')

    def __str__(self):
        return str(self.name)

Blog/app/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Article, Category


# Create your views here.

def main(request):
    return render(request, 'main.html')


class ArticleListView(ListView):
    model = Article
    queryset = Article.objects.all()
    template_name = "main.html"
    paginate_by = 9

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


class ArticleListCategoryView(ListView):
    template_name = "main.html"
    paginate_by = 9

    def get_queryset(self):
        cat = Category.objects.get(category_slug=self.kwargs['slug'])
        return Article.objects.filter(article_category=cat)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


class ArticleDetailView(DetailView):
    model = Article
    template_name = "article.html"
    slug_field = 'article_slug'

Blog/app/templates/article.html
{% extends 'index.html' %}

{% block content %}

	
	<div class="container">
	  <div class="row justify-content-md-center">
		<div class="col-md-auto header">
			{% include 'social.html' %}
		</div>
	  </div>
	</div>


	<div class="container">
	  <div class="row justify-content-md-center">
		<div class="col-md-8">
		<h3>{{article.article_title}}</h3><br>
			{{article.article_content|safe}}
		</div>
	  </div>
	</div>
{% endblock content %}

Blog/app/templates/footer.html
<footer>
  <span>arzaev_dev</span>
</footer>

Blog/app/templates/header.html
{% load static %}
<img class="me " src="{% static 'images/face.jpg' %}" alt="" style="height: 100px; width: 100px"/>

{% include 'social.html' %}

Blog/app/templates/index.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/articles.css' %}" rel="stylesheet">
    <link href="{% static 'css/pagination.css' %}" rel="stylesheet">
    <link href="{% static 'css/footer.css' %}" rel="stylesheet">
    <link href="{% static 'css/rainbow.css' %}" rel="stylesheet">

	<link href="https://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>
    <title>Arzaev Dev!</title>
  </head>
  <body>


<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
  <!--      <li class="nav-item">
          <a class="nav-link" aria-current="page" href="#">Кто</a>
        </li> -->
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Главная</a>
        </li>
      <!--  <li class="nav-item">
          <a class="nav-link" aria-current="page" href="#">Проекты</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           Язык 
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="#">EN</a></li>
            <li><a class="dropdown-item" href="#">RU</a></li>
          </ul> -->
        </li>
      </ul>
    </div>
  </div>
</nav>


	{% block content %}

	{% endblock %}

		{% include 'footer.html' %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js"></script>
	<script type="text/javascript" src="{% static 'js/wow.js' %}"></script> -->
	<script type="text/javascript" src="{% static 'js/rainbow-custom.min.js' %}"></script>
  </body>
</html>

Blog/app/templates/main.html
{% extends 'index.html' %}





{% block content %}

	<div class="container">
	  <div class="row justify-content-md-center">
		<div class="col-md-8 header">
			{% include 'header.html' %}
			
			<ul class="menu"> 
{% for category in categories %}
<li>
<a href="/category/{{category.category_slug}}" class="link-secondary" title="Home page">{{category.category_name}}</a>
</li>
{% endfor %}
</ul>
		</div>
	  </div>
	</div>


<section class="layout-article">
  <ul class="box-article">
	{% for article in article_list %}
    <li class="list-article wow flipInY">
      <article class="box-article"><a href="/{{article.article_slug}}/">
          <h1>{{article.article_title}}</h1>
          <figure><img src="{{article.article_header_image_url}}" alt=""/></figure>
          <p>{{article.article_description}}</p></a></article>
    </li>
	{% endfor %}
  </ul>
</section>

{% include 'pagination.html' %}


{% endblock content %}

Blog/app/templates/pagination.html
<nav data-pagination>
<ul class="pagination ">
    {% if page_obj.has_previous %}
        {% if page_obj.number|add:'-3' > 1 %}
            <li>
                <a href="?{{ material }}{{ size }}{{ min_filter_price }}{{ max_filter_price }}page=1">1</a>
            </li>
        {% endif %}
        {% if page_obj.number|add:'-3' >= 3 %}
            <li>
                    <a href="?{{ material }}{{ size }}{{ min_filter_price }}{{ max_filter_price }}page={{ page_obj.previous_page_number|add:'-3' }}">
                <span class="pagination__link">• • •</span>
                </a>
            </li>
        {% endif %}
    {% endif %}
    {% if paginator.page_range|length > 1 %}
        {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="current">
                    <a href="#">{{ i }}</a>
                </li>
            {% elif i > page_obj.number|add:'-4' and i < page_obj.number|add:'4' %}
                <li>
                        <a href="?{{ material }}{{ size }}{{ min_filter_price }}{{ max_filter_price }}page={{ i }}">{{ i }}</a>
                </li>
            {% endif %}
        {% endfor %}
    {% endif %}
    {% if page_obj.has_next %}
        {% if page_obj.number|add:'4' < page_obj.paginator.num_pages %}
            <li>
                    <a href="?{{ material }}{{ size }}{{ min_filter_price }}{{ max_filter_price }}page={{ page_obj.next_page_number|add:'3' }}">
                <span class="pagination__link">• • •</span>
                </a>
            </li>
        {% endif %}
        {% if page_obj.number|add:'3' < page_obj.paginator.num_pages %}
            <li>
                    <a href="?{{ material }}{{ size }}{{ min_filter_price }}{{ max_filter_price }}page={{ page_obj.paginator.num_pages }}">
                        {{ page_obj.paginator.num_pages }}
                    </a>
            </li>
        {% endif %}
    {% endif %}
</ul>
</nav>

Blog/app/templates/social.html
<div class="social">
<!--  <a href=""><i id="twitter" class="icon-twitter"></i></a>-->
  <a href="https://github.com/arzaev"><i id="github" class="icon-github"></i></a>
<!--  <i id="stack" class="icon-stackexchange"></i>-->
<!--  <i id="code" class="icon-code"></i>-->
  <a href="mailto: email@arzaev.com"><i id="mail" class="icon-envelope"></i> </a>
  <a href="https://www.youtube.com/channel/UCV7Qm_7VBmnkuwFFfAIn8FQ"> <i id="youtube" class="icon-youtube"></i> </a>
</div>